[package.build.source]
git = "https://github.com/frankarobotics/libfranka.git"

# libfranka 0.20.4 commit hash
rev = "95b406f47c97cedfbe426c04d8fb7f83a9885e1c"

[package.build.backend]
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/robostack-jazzy",
  "https://prefix.dev/conda-forge",
]
name = "pixi-build-cmake"
version = "*"

[package.build.config]
extra-args = [
    "-DBUILD_TESTS=OFF",
    "-DBUILD_EXAMPLES=OFF",
    "-DCMAKE_BUILD_TYPE=Release",
    "-DEIGEN3_INCLUDE_DIRS=$PREFIX/include/eigen3",
    "-DCMAKE_POLICY_VERSION_MINIMUM=3.5",
]

[package]
name = "libfranka"
version = "0.20.4"

# Libraries required during build (link against these)
[package.host-dependencies]
console_bridge = ">=1.0"
eigen = ">=3.4"
poco = ">=1.12"
pinocchio = ">=3.0"
tinyxml2 = ">=10.0"
urdfdom = ">=4.0.1,<4.1.0a0"
fmt = ">=11.0"

# Runtime shared libraries
[package.run-dependencies]
poco = ">=1.12"
pinocchio = ">=3.0"
tinyxml2 = ">=10.0"
urdfdom = ">=4.0.1,<4.1.0a0"
console_bridge = ">=1.0"
fmt = ">=11.0"

[workspace]
channels = [
  "https://prefix.dev/robostack-jazzy",
  "https://prefix.dev/conda-forge",
]
platforms = ["linux-64"]
preview = ["pixi-build"]

[dependencies]
libfranka = { path = "." }
