[package.build.source]
git = "https://github.com/frankarobotics/franka_ros2.git"
rev = "ce8cc0bd853092b936be12f97895fb31294a5743"
subdirectory = "franka_msgs"

[package.build.backend]
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/robostack-jazzy",
  "https://prefix.dev/conda-forge",
]
name = "pixi-build-ros"
version = "*"

[package]
name = "ros-jazzy-franka-msgs"
version = "3.2.2"

[package.build.config]
distro = "jazzy"

[package.build-dependencies]
ros2-distro-mutex = "0.14.*"

[package.host-dependencies]
ros2-distro-mutex = "0.14.*"

[package.run-dependencies]
ros2-distro-mutex = "0.14.*"

[workspace]
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/robostack-jazzy",
  "https://prefix.dev/conda-forge",
]
platforms = ["linux-64"]
preview = ["pixi-build"]
