[workspace]
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/robostack-jazzy",
  "https://prefix.dev/conda-forge",
]
platforms = ["linux-64"]
preview = ["pixi-build"]

[dependencies]
libfranka = { path = "../libfranka" }
ros-jazzy-franka-description = { path = "../franka_description" }

ros-jazzy-franka-msgs = { path = "franka_msgs" }
ros-jazzy-franka-hardware = { path = "franka_hardware" }
ros-jazzy-franka-gripper = { path = "franka_gripper" }
ros-jazzy-franka-selfcollision = { path = "franka_selfcollision" }
ros-jazzy-franka-semantic-components = { path = "franka_semantic_components" }
ros-jazzy-franka-robot-state-broadcaster = { path = "franka_robot_state_broadcaster" }
ros-jazzy-franka-example-controllers = { path = "franka_example_controllers" }
ros-jazzy-franka-bringup = { path = "franka_bringup" }
ros-jazzy-franka-fr3-moveit-config = { path = "franka_fr3_moveit_config" }
