[package.build.source]
git = "https://github.com/XingxinHE/moveit_calibration.git"
rev = "9bf31843963c50f87d3bc439416e552220b156fe"
subdirectory = "moveit_calibration_gui"

[package.build.backend]
channels = [
    "https://prefix.dev/pixi-build-backends",
    "https://prefix.dev/robostack-jazzy",
    "https://prefix.dev/conda-forge"
]
name = "pixi-build-ros"
version = "*"

[package.build.config]
distro = "jazzy"
extra-package-mappings = [
    { "libopencv-dev" = { conda = "libopencv >=4.12,<4.13" } },
]

[package]
name = "ros-jazzy-moveit-calibration-gui"
version = "2.0.0"

[package.build-dependencies]
python = "3.12.*"
ros-jazzy-moveit-calibration-plugins = { path = "../moveit_calibration_plugins" }

[package.host-dependencies]
python = "3.12.*"
ros-jazzy-moveit-calibration-plugins = { path = "../moveit_calibration_plugins" }

[package.run-dependencies]
ros-jazzy-moveit-calibration-plugins = { path = "../moveit_calibration_plugins" }

[workspace]
channels = [
    "https://prefix.dev/robostack-jazzy",
    "https://prefix.dev/conda-forge"
]
platforms = ["linux-64"]
preview = ["pixi-build"]

[dependencies]
ros-jazzy-moveit-calibration-gui = { path = "." }
