[package.build.source]
git = "https://github.com/frankarobotics/franka_ros2.git"
rev = "ce8cc0bd853092b936be12f97895fb31294a5743"
subdirectory = "franka_example_controllers"

[package.build.backend]
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/robostack-jazzy",
  "https://prefix.dev/conda-forge",
]
name = "pixi-build-ros"
version = "*"

[package.build.config]
distro = "jazzy"
extra-package-mappings = [
    { libfranka = { conda = "libfranka" } },
]

[package.build-dependencies]
ros-jazzy-franka-msgs = { path = "../franka_msgs" }
ros-jazzy-franka-selfcollision = { path = "../franka_selfcollision" }
ros-jazzy-franka-semantic-components = { path = "../franka_semantic_components" }

[package.host-dependencies]
libfranka = { path = "../../libfranka" }
ros-jazzy-franka-msgs = { path = "../franka_msgs" }
ros-jazzy-franka-selfcollision = { path = "../franka_selfcollision" }
ros-jazzy-franka-semantic-components = { path = "../franka_semantic_components" }
ros-jazzy-ament-index-cpp = "*"
ros-jazzy-hardware-interface = "*"
ros-jazzy-moveit-core = "*"
ros-jazzy-moveit-msgs = "*"
ros-jazzy-rclcpp-action = "*"
eigen = "*"

[package.run-dependencies]
libfranka = { path = "../../libfranka" }
ros-jazzy-franka-msgs = { path = "../franka_msgs" }
ros-jazzy-franka-selfcollision = { path = "../franka_selfcollision" }
ros-jazzy-franka-semantic-components = { path = "../franka_semantic_components" }

[workspace]
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/robostack-jazzy",
  "https://prefix.dev/conda-forge",
]
platforms = ["linux-64"]
preview = ["pixi-build"]
